fmod NATU is sort Natu .
  op 0     : -> Natu [ctor] .
  op s     : Natu -> Natu [ctor] .
  op _+_   : Natu Natu -> Natu [comm] .
  op _*_   : Natu Natu -> Natu .
  op _^_   : Natu Natu -> Natu .

  eq X:Natu + 0 = X:Natu .
  eq X:Natu + s(Y:Natu) = s(X:Natu + Y:Natu) .
  eq X:Natu * 0 = (0).Natu .
  eq X:Natu * s(Y:Natu) = (X:Natu * Y:Natu) + X:Natu .
  eq X:Natu ^ 0 = (s(0)).Natu .
  eq X:Natu ^ s(Y:Natu) = X:Natu * (X:Natu ^ Y:Natu) .
endfm