fmod NAT-MIXFIX is
    sort Natural .
    op 0 : -> Natural [ctor] .
    op s_ : Natural -> Natural [ctor] .
    op _+_ : Natural Natural -> Natural .
    op _*_ : Natural Natural -> Natural .
    vars N M : Natural .
    eq N + 0 = N .
    eq N + s M = s(N + M) .
    eq N * 0 = 0 .
    eq N * s M = N + (N * M) .
endfm

--- Tests
--- =====

--- Addition
reduce s s 0 + s s 0        == s s s s 0 .

quit
